version: "3"
services:
  web:
    build: ./server/nginx
    ports:
      - "80:80"
    volumes:
      - ./server/app:/var/www
      - ./server/nginx/conf.d:/etc/nginx/conf.d

  app:
    build:
      context: ./server/app
      dockerfile: Dockerfile
    depends_on:
      - web
    volumes:
      - ./server/app:/var/www
      - ./server/app/.env:/var/www/.env
